<template>
  <div class="generator-wireframe">
    <h1>Generate Paragraphs with AI!</h1>
    <p class="subtitle">Input a topic and instantly get paragraphs generated by AI.</p>

    <!-- Topic Input -->
    <div class="input-group">
      <input 
        v-model="topic"
        type="text"
        placeholder="🔍 Enter your topic..."
        class="topic-input"
        @keyup.enter="generateContent"
      />
    </div>

    <!-- Dropdowns Row -->
    <div class="dropdowns-row">
      <select v-model="contentType" class="dropdown">
        <option disabled value="">Content Type</option>
        <option value="paragraph">Paragraph</option>
        <option value="essay">Essay</option>
        <option value="letter">Letter</option>
        <option value="summary">Summary</option>
        <option value="report">Report</option>
      </select>

      <select v-model="tone" class="dropdown">
        <option disabled value="">Tone</option>
        <option value="academic">Academic</option>
        <option value="casual">Casual</option>
        <option value="professional">Professional</option>
        <option value="creative">Creative</option>
        <option value="persuasive">Persuasive</option>
      </select>

      <select v-model="length" class="dropdown">
        <option disabled value="">Length</option>
        <option value="short">Short</option>
        <option value="medium">Medium</option>
        <option value="long">Long</option>
      </select>
    </div>

    <!-- Generate Button -->
    <button 
      @click="generateContent"
      :disabled="loading || !topic.trim()"
      class="generate-btn"
    >
      {{ loading ? 'Generating...' : 'Generate' }}
    </button>

    <!-- Error Message -->
    <div v-if="error" class="error-message">
      ⚠️ {{ error }}
    </div>

    <!-- Debug Info (Optional - remove in production) -->
    <div v-if="debugPrompt" class="debug-info">
      <small>Prompt sent: "{{ debugPrompt }}"</small>
    </div>

    <!-- Output Section -->
    <div v-if="showOutput" class="output-section">
      <h2>Generated Output</h2>
      <div class="output-content">
        <p>{{ result }}</p>
      </div>
      
      <div class="output-actions">
        <button @click="copyToClipboard" class="action-btn">
          📋 Copy
        </button>
        <button @click="generateNew" class="action-btn secondary">
          🔄 New
        </button>
      </div>
    </div>

    <!-- Loading State -->
    <div v-if="loading" class="loading-state">
      <div class="spinner"></div>
      <p>AI is writing...</p>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'

// State
const topic = ref('')
const contentType = ref('paragraph')
const tone = ref('academic')
const length = ref('medium')
const result = ref('')
const debugPrompt = ref('')
const loading = ref(false)
const showOutput = ref(false)
const error = ref('')

const API_URL = 'http://localhost:3000/api/generate'

// Map length to word count
const lengthMap = {
  short: 100,
  medium: 250,
  long: 500
}

const generateContent = async () => {
  // Reset
  error.value = ''
  result.value = ''
  showOutput.value = false
  debugPrompt.value = ''
  
  // Validation
  if (!topic.value.trim()) {
    error.value = 'Please enter a topic'
    return
  }

  loading.value = true

  try {
    const wordCount = lengthMap[length.value] || 250
    
    // Build the EXACT prompt structure you requested
    const prompt = `write a ${contentType.value} about ${topic.value} around ${wordCount} words in a ${tone.value} tone`
    debugPrompt.value = prompt // For debugging
    
    console.log('Sending prompt:', prompt)
    
    // Send to backend
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        topic: topic.value,           // Send topic
        prompt: prompt,               // Also send the constructed prompt
        contentType: contentType.value,
        tone: tone.value,
        wordCount: wordCount
      })
    })

    const data = await response.json()
    console.log('Response:', data)

    if (!response.ok) {
      throw new Error(data.message || `HTTP error ${response.status}`)
    }

    if (data.success) {
      result.value = data.result
      showOutput.value = true
    } else {
      error.value = data.message || 'Failed to generate content'
    }

  } catch (err) {
    console.error('Error:', err)
    error.value = `Error: ${err.message}`
    
    // Test with direct fetch to debug
    await testBackendConnection()
  } finally {
    loading.value = false
  }
}

// Debug function to test backend
const testBackendConnection = async () => {
  try {
    console.log('Testing backend connection...')
    
    // Test health endpoint
    const health = await fetch('http://localhost:3000/')
    console.log('Health check:', await health.text())
    
    // Test with simple prompt
    const testResponse = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        prompt: 'write a paragraph about AI around 100 words in a casual tone'
      })
    })
    
    const testData = await testResponse.json()
    console.log('Test response:', testData)
    
    if (testResponse.ok) {
      error.value = 'Backend works! Try your topic again.'
    }
  } catch (testErr) {
    console.error('Backend test failed:', testErr)
    error.value = `Cannot connect to backend at ${API_URL}. Make sure it's running.`
  }
}

const copyToClipboard = async () => {
  try {
    await navigator.clipboard.writeText(result.value)
    alert('✅ Copied!')
  } catch (err) {
    error.value = 'Failed to copy'
  }
}

const generateNew = () => {
  topic.value = ''
  result.value = ''
  showOutput.value = false
  error.value = ''
}
</script>

<style scoped>
.generator-wireframe {
  background: white;
  padding: 40px;
  border-radius: 12px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
  margin-bottom: 40px;
  position: relative;
}

.generator-wireframe h1 {
  margin-bottom: 10px;
  color: #333;
  font-size: 2rem;
  font-weight: 700;
}

.subtitle {
  color: #666;
  margin-bottom: 30px;
  font-size: 1.1rem;
}

.input-group {
  margin-bottom: 20px;
}

.topic-input {
  width: 100%;
  padding: 15px 20px;
  font-size: 16px;
  border: 2px solid #e0e0e0;
  border-radius: 8px;
  transition: border-color 0.3s;
}

.topic-input:focus {
  outline: none;
  border-color: #667eea;
}

.dropdowns-row {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 15px;
  margin-bottom: 20px;
}

@media (max-width: 768px) {
  .dropdowns-row {
    grid-template-columns: 1fr;
  }
}

.dropdown {
  width: 100%;
  padding: 15px;
  font-size: 16px;
  border: 2px solid #e0e0e0;
  border-radius: 8px;
  background: white;
  cursor: pointer;
  appearance: none;
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='%23333' viewBox='0 0 16 16'%3E%3Cpath d='M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z'/%3E%3C/svg%3E");
  background-repeat: no-repeat;
  background-position: right 15px center;
  background-size: 16px;
}

.dropdown:focus {
  outline: none;
  border-color: #667eea;
}

.generate-btn {
  width: 100%;
  padding: 16px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  border: none;
  border-radius: 8px;
  font-size: 16px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.3s;
  margin-top: 10px;
}

.generate-btn:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 8px 25px rgba(102, 126, 234, 0.3);
}

.generate-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.error-message {
  margin-top: 15px;
  padding: 12px 20px;
  background: #ffeaea;
  border-left: 4px solid #e74c3c;
  border-radius: 6px;
  color: #c0392b;
  font-size: 0.95em;
}

.debug-info {
  margin-top: 10px;
  padding: 10px;
  background: #f0f0f0;
  border-radius: 6px;
  font-size: 0.9em;
  color: #666;
}

.output-section {
  margin-top: 30px;
  padding: 25px;
  background: #f9f9f9;
  border-radius: 8px;
  border: 1px solid #e0e0e0;
  animation: fadeIn 0.5s ease;
}

.output-section h2 {
  margin-bottom: 20px;
  color: #333;
  font-size: 1.4rem;
}

.output-content {
  background: white;
  padding: 25px;
  border-radius: 6px;
  margin-bottom: 20px;
  line-height: 1.7;
  font-size: 1.05em;
}

.output-actions {
  display: flex;
  gap: 10px;
}

.action-btn {
  padding: 10px 20px;
  border: 2px solid #667eea;
  background: white;
  color: #667eea;
  border-radius: 6px;
  cursor: pointer;
  font-weight: 600;
  transition: all 0.3s;
}

.action-btn:hover {
  background: #667eea;
  color: white;
}

.action-btn.secondary {
  border-color: #95a5a6;
  color: #95a5a6;
}

.action-btn.secondary:hover {
  background: #95a5a6;
  color: white;
}

.loading-state {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(255, 255, 255, 0.9);
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  border-radius: 12px;
}

.spinner {
  width: 40px;
  height: 40px;
  border: 4px solid #f3f3f3;
  border-top: 4px solid #667eea;
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin-bottom: 15px;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

@keyframes fadeIn {
  from { opacity: 0; transform: translateY(20px); }
  to { opacity: 1; transform: translateY(0); }
}
</style>