<template>
  <div class="header-section">
    <h1>Generate Paragraphs with AI!</h1>
    <p class="subtitle">Input a topic and instantly get paragraphs generated by AI.</p>
  </div>
</template>

<script setup>
// No logic needed, just presentation
</script>

<style scoped>
.header-section {
  margin-bottom: 30px;
}

h1 {
  margin-bottom: 10px;
  color: #333;
  font-size: 2rem;
  font-weight: 700;
}

.subtitle {
  color: #666;
  margin-bottom: 30px;
  font-size: 1.1rem;
}
</style>