<template>
  <div class="generator-wireframe">
    <h1>Generate Paragraphs with AI!</h1>
    <p class="subtitle">Input a topic and instantly get paragraphs generated by AI.</p>

    <!-- Topic Input -->
    <div class="input-group">
      <input 
        v-model="topic"
        type="text"
        placeholder="🔍 Enter your topic..."
        class="topic-input"
        @keyup.enter="generateContent"
      />
    </div>

    <!-- Dropdowns Row -->
    <div class="dropdowns-row">
      <select v-model="contentType" class="dropdown">
        <option disabled value="">Content Type</option>
        <option value="paragraph">Paragraph</option>
        <option value="essay">Essay</option>
        <option value="letter">Letter</option>
        <option value="summary">Summary</option>
        <option value="report">Report</option>
      </select>

      <select v-model="tone" class="dropdown">
        <option disabled value="">Tone</option>
        <option value="academic">Academic</option>
        <option value="casual">Casual</option>
        <option value="professional">Professional</option>
        <option value="creative">Creative</option>
        <option value="persuasive">Persuasive</option>
      </select>

      <select v-model="length" class="dropdown">
        <option disabled value="">Length</option>
        <option value="short">Short</option>
        <option value="medium">Medium</option>
        <option value="long">Long</option>
      </select>
    </div>

    <!-- Generate Button -->
    <button 
      @click="generateContent"
      :disabled="loading || !topic.trim()"
      class="generate-btn"
    >
      {{ loading ? 'Generating...' : 'Generate' }}
    </button>

    <!-- Error Message -->
    <div v-if="error" class="error-message">
      ⚠️ {{ error }}
    </div>

    <!-- Output Section -->
    <div v-if="showOutput" class="output-section">
      <div class="output-header">
        <h2>📝 Generated Output</h2>
        <div class="output-stats">
          <span class="stat-badge">📊 {{ wordCount }} words</span>
          <span class="stat-badge">📄 {{ contentType }}</span>
          <span class="stat-badge">🎭 {{ tone }}</span>
        </div>
      </div>
      
      <div class="output-content">
        <p>{{ result }}</p>
      </div>
      
      <!-- Export Actions -->
      <div class="export-actions">
        <h3>📤 Export Options</h3>
        <div class="action-buttons">
          <button @click="copyToClipboard" class="action-btn">
            <span class="btn-icon">📋</span>
            <span>Copy Text</span>
          </button>
          
          <button @click="downloadPDF" class="action-btn primary">
            <span class="btn-icon">📄</span>
            <span>Export as PDF</span>
          </button>
          
          <button @click="downloadTXT" class="action-btn">
            <span class="btn-icon">📝</span>
            <span>Save as TXT</span>
          </button>
          
          <button @click="generateNew" class="action-btn secondary">
            <span class="btn-icon">🔄</span>
            <span>New Content</span>
          </button>
        </div>
      </div>
    </div>

    <!-- Loading State -->
    <div v-if="loading" class="loading-state">
      <div class="spinner"></div>
      <p>AI is writing your content...</p>
    </div>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'

// State
const topic = ref('')
const contentType = ref('paragraph')
const tone = ref('academic')
const length = ref('medium')
const result = ref('')
const loading = ref(false)
const showOutput = ref(false)
const error = ref('')

const API_URL = 'http://localhost:3000/api/generate'

// Map length to word count
const lengthMap = {
  short: 100,
  medium: 250,
  long: 500
}

// Computed properties
const wordCount = computed(() => {
  return result.value ? result.value.trim().split(/\s+/).length : 0
})

const generateContent = async () => {
  error.value = ''
  result.value = ''
  showOutput.value = false
  
  if (!topic.value.trim()) {
    error.value = 'Please enter a topic'
    return
  }

  loading.value = true

  try {
    const wordCount = lengthMap[length.value] || 250
    
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        topic: topic.value,
        contentType: contentType.value,
        tone: tone.value,
        wordCount: wordCount
      })
    })

    const data = await response.json()

    if (!response.ok) {
      throw new Error(data.message || `HTTP error ${response.status}`)
    }

    if (data.success) {
      result.value = data.result
      showOutput.value = true
    } else {
      error.value = data.message || 'Failed to generate content'
    }

  } catch (err) {
    console.error('Error:', err)
    error.value = `Error: ${err.message}`
  } finally {
    loading.value = false
  }
}

const copyToClipboard = async () => {
  try {
    await navigator.clipboard.writeText(result.value)
    alert('✅ Copied to clipboard!')
  } catch (err) {
    error.value = 'Failed to copy to clipboard'
  }
}

const downloadTXT = () => {
  const content = `
CACTUS-PEN AI GENERATED CONTENT
================================
Topic: ${topic.value}
Type: ${contentType.value}
Tone: ${tone.value}
Length: ${length.value}
Word Count: ${wordCount.value}
Generated: ${new Date().toLocaleString()}

${result.value}
================================
Generated by CactusPen AI - Free AI writing assistant
  `
  
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `cactuspen-${Date.now()}.txt`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

const downloadPDF = () => {
  try {
    // Create a simple HTML page for printing
    const pdfContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>CactusPen AI - Generated Content</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          line-height: 1.6;
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
          color: #333;
        }
        .header {
          text-align: center;
          margin-bottom: 30px;
          padding-bottom: 20px;
          border-bottom: 3px solid #2ecc71;
        }
        .header h1 {
          color: #2c3e50;
          margin-bottom: 10px;
        }
        .metadata {
          background: #f8f9fa;
          padding: 15px;
          border-radius: 8px;
          margin-bottom: 30px;
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
          gap: 10px;
        }
        .metadata-item {
          display: flex;
          flex-direction: column;
        }
        .metadata-label {
          font-weight: bold;
          color: #666;
          font-size: 0.9em;
        }
        .metadata-value {
          font-size: 1.1em;
          color: #2c3e50;
        }
        .content {
          font-size: 14px;
          line-height: 1.8;
          text-align: justify;
        }
        .footer {
          margin-top: 50px;
          padding-top: 20px;
          border-top: 1px solid #eee;
          text-align: center;
          color: #666;
          font-size: 0.9em;
        }
        @media print {
          body {
            padding: 0;
          }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>🌵 CactusPen AI</h1>
        <p>AI-Powered Writing Assistant</p>
      </div>
      
      <div class="metadata">
        <div class="metadata-item">
          <span class="metadata-label">Topic:</span>
          <span class="metadata-value">${topic.value}</span>
        </div>
        <div class="metadata-item">
          <span class="metadata-label">Content Type:</span>
          <span class="metadata-value">${contentType.value}</span>
        </div>
        <div class="metadata-item">
          <span class="metadata-label">Tone:</span>
          <span class="metadata-value">${tone.value}</span>
        </div>
        <div class="metadata-item">
          <span class="metadata-label">Word Count:</span>
          <span class="metadata-value">${wordCount.value}</span>
        </div>
        <div class="metadata-item">
          <span class="metadata-label">Generated:</span>
          <span class="metadata-value">${new Date().toLocaleString()}</span>
        </div>
      </div>
      
      <div class="content">
        ${result.value.replace(/\n/g, '<br>')}
      </div>
      
      <div class="footer">
        <p>Generated by CactusPen AI - Free AI writing assistant for students</p>
        <p>🌵 No login required • 📄 PDF Export • 🔒 Privacy First</p>
      </div>
    </body>
    </html>
    `
    
    // Open print dialog
    const printWindow = window.open('', '_blank')
    printWindow.document.write(pdfContent)
    printWindow.document.close()
    
    // Wait for content to load, then trigger print
    printWindow.onload = function() {
      printWindow.print()
      printWindow.onafterprint = function() {
        printWindow.close()
      }
    }
    
  } catch (err) {
    console.error('PDF generation error:', err)
    error.value = 'Failed to generate PDF. Please try again.'
  }
}

const generateNew = () => {
  topic.value = ''
  result.value = ''
  showOutput.value = false
  error.value = ''
  contentType.value = 'paragraph'
  tone.value = 'academic'
  length.value = 'medium'
}
</script>

<style scoped>
.generator-wireframe {
  background: white;
  padding: 40px;
  border-radius: 12px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
  margin-bottom: 40px;
  position: relative;
}

.generator-wireframe h1 {
  margin-bottom: 10px;
  color: #333;
  font-size: 2rem;
  font-weight: 700;
}

.subtitle {
  color: #666;
  margin-bottom: 30px;
  font-size: 1.1rem;
}

.input-group {
  margin-bottom: 20px;
}

.topic-input {
  width: 100%;
  padding: 15px 20px;
  font-size: 16px;
  border: 2px solid #e0e0e0;
  border-radius: 8px;
  transition: border-color 0.3s;
}

.topic-input:focus {
  outline: none;
  border-color: #667eea;
}

.dropdowns-row {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 15px;
  margin-bottom: 20px;
}

@media (max-width: 768px) {
  .dropdowns-row {
    grid-template-columns: 1fr;
  }
}

.dropdown {
  width: 100%;
  padding: 15px;
  font-size: 16px;
  border: 2px solid #e0e0e0;
  border-radius: 8px;
  background: white;
  cursor: pointer;
  appearance: none;
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='%23333' viewBox='0 0 16 16'%3E%3Cpath d='M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z'/%3E%3C/svg%3E");
  background-repeat: no-repeat;
  background-position: right 15px center;
  background-size: 16px;
}

.dropdown:focus {
  outline: none;
  border-color: #667eea;
}

.generate-btn {
  width: 100%;
  padding: 16px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  border: none;
  border-radius: 8px;
  font-size: 16px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.3s;
  margin-top: 10px;
}

.generate-btn:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 8px 25px rgba(102, 126, 234, 0.3);
}

.generate-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.error-message {
  margin-top: 15px;
  padding: 12px 20px;
  background: #ffeaea;
  border-left: 4px solid #e74c3c;
  border-radius: 6px;
  color: #c0392b;
  font-size: 0.95em;
}

.output-section {
  margin-top: 30px;
  padding: 25px;
  background: #f9f9f9;
  border-radius: 8px;
  border: 1px solid #e0e0e0;
  animation: fadeIn 0.5s ease;
}

.output-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  flex-wrap: wrap;
  gap: 15px;
}

.output-header h2 {
  color: #333;
  font-size: 1.4rem;
  margin: 0;
}

.output-stats {
  display: flex;
  gap: 10px;
  flex-wrap: wrap;
}

.stat-badge {
  padding: 6px 12px;
  background: white;
  border-radius: 20px;
  font-size: 0.85em;
  font-weight: 500;
  color: #555;
  border: 1px solid #ddd;
  display: flex;
  align-items: center;
  gap: 5px;
}

.output-content {
  background: white;
  padding: 25px;
  border-radius: 6px;
  margin-bottom: 30px;
  line-height: 1.7;
  font-size: 1.05em;
  white-space: pre-wrap;
  border: 1px solid #e0e0e0;
}

.export-actions {
  padding-top: 20px;
  border-top: 2px solid #e0e0e0;
}

.export-actions h3 {
  margin-bottom: 20px;
  color: #333;
  font-size: 1.2rem;
  display: flex;
  align-items: center;
  gap: 10px;
}

.action-buttons {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 15px;
}

.action-btn {
  padding: 15px;
  border: 2px solid #e0e0e0;
  background: white;
  color: #333;
  border-radius: 8px;
  cursor: pointer;
  font-weight: 600;
  transition: all 0.3s;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
}

.action-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);
  border-color: #667eea;
}

.action-btn.primary {
  border-color: #667eea;
  background: #667eea;
  color: white;
}

.action-btn.primary:hover {
  background: #5a6fd8;
  border-color: #5a6fd8;
}

.action-btn.secondary {
  border-color: #95a5a6;
  color: #95a5a6;
}

.action-btn.secondary:hover {
  background: #95a5a6;
  color: white;
}

.btn-icon {
  font-size: 1.2em;
}

.loading-state {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(255, 255, 255, 0.95);
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  border-radius: 12px;
  z-index: 10;
}

.spinner {
  width: 40px;
  height: 40px;
  border: 4px solid #f3f3f3;
  border-top: 4px solid #667eea;
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin-bottom: 20px;
}

.loading-state p {
  color: #333;
  font-size: 1.1em;
  font-weight: 500;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

@keyframes fadeIn {
  from { opacity: 0; transform: translateY(20px); }
  to { opacity: 1; transform: translateY(0); }
}
</style>