import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

export const useGeneratorStore = defineStore('generator', () => {
  // State
  const topic = ref('')
  const context = ref('')
  const contentType = ref('paragraph')
  const tone = ref('academic')
  const difficulty = ref('medium')
  const wordCount = ref(250)
  const result = ref('')
  const loading = ref(false)
  const showOutput = ref(false)
  const error = ref('')

  // API URL
  const API_URL = 'http://localhost:3000/api/generate'

  // Getters (computed)
  const wordCountDisplay = computed(() => {
    return result.value ? result.value.trim().split(/\s+/).length : wordCount.value
  })

  // Actions
  async function generateContent() {
    error.value = ''
    result.value = ''
    showOutput.value = false
    
    if (!topic.value.trim()) {
      error.value = 'Please enter a topic'
      return
    }

    loading.value = true

    try {
      const response = await fetch(API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topic: topic.value,
          context: context.value,
          contentType: contentType.value,
          tone: tone.value,
          difficulty: difficulty.value,
          wordCount: wordCount.value
        })
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.message || `HTTP error ${response.status}`)
      }

      if (data.success) {
        result.value = data.result
        showOutput.value = true
      } else {
        error.value = data.message || 'Failed to generate content'
      }

    } catch (err) {
      console.error('Error:', err)
      error.value = `Error: ${err.message}. Make sure the backend server is running.`
    } finally {
      loading.value = false
    }
  }

  async function copyToClipboard() {
    try {
      await navigator.clipboard.writeText(result.value)
      return true
    } catch (err) {
      error.value = 'Failed to copy to clipboard'
      return false
    }
  }

  function downloadTXT() {
    const content = `
CACTUS-PEN AI GENERATED CONTENT
================================
Topic: ${topic.value}
Context: ${context.value || 'None'}
Type: ${contentType.value}
Tone: ${tone.value}
Difficulty: ${difficulty.value}
Target Word Count: ${wordCount.value}
Generated: ${new Date().toLocaleString()}

${result.value}
================================
Generated by CactusPen AI - Free AI writing assistant
    `
    
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `cactuspen-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  function downloadPDF() {
    try {
      const pdfContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Cactus-Pen </title>
        <style>
          body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
          }
          .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 3px solid #0aecd0;
          }
          .header h1 {
            color: #1a2a24;
            margin-bottom: 10px;
          }
          .metadata {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 30px;
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 10px;
          }
          .metadata-item {
            display: flex;
            flex-direction: column;
          }
          .metadata-label {
            font-weight: bold;
            color: #666;
            font-size: 0.9em;
          }
          .metadata-value {
            font-size: .5rem;
            color: #1a2a24;
          }
          .content {
            font-size: 14px;
            line-height: 1.8;
            text-align: justify;
          }
          .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            text-align: center;
            color: #666;
            font-size: 0.9em;
          }
          @media print {
            body {
              padding: 0;
            }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>🌵 Cactus-Pen </h1>
          <p>Your writing assistant....</p>S
        </div>
        
        <div class="metadata">
          <div class="metadata-item">
            <span class="metadata-label">Topic:</span>
            <span class="metadata-value">${topic.value}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Context:</span>
            <span class="metadata-value">${context.value || 'None'}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Content Type:</span>
            <span class="metadata-value">${contentType.value}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Tone:</span>
            <span class="metadata-value">${tone.value}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Difficulty:</span>
            <span class="metadata-value">${difficulty.value}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Word Count:</span>
            <span class="metadata-value">${wordCountDisplay.value}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Generated:</span>
            <span class="metadata-value">${new Date().toLocaleString()}</span>
          </div>
        </div>
        
        <div class="content">
          ${result.value.replace(/\n/g, '<br>')}
        </div>
        
        <div class="footer">
          <p>Generated by CactusPen AI - Free AI writing assistant for students</p>
          <p>🌵 No login required • 📄 PDF Export • 🔒 Privacy First</p>
        </div>
      </body>
      </html>
      `
      
      const printWindow = window.open('', '_blank')
      printWindow.document.write(pdfContent)
      printWindow.document.close()
      
      printWindow.onload = function() {
        printWindow.print()
        printWindow.onafterprint = function() {
          printWindow.close()
        }
      }
      
    } catch (err) {
      console.error('PDF generation error:', err)
      error.value = 'Failed to generate PDF. Please try again.'
    }
  }

  function shareContent() {
    if (navigator.share) {
      navigator.share({
        title: `CactusPen AI: ${topic.value}`,
        text: result.value.substring(0, 100) + '...',
        url: window.location.href,
      })
      .catch(console.error)
    } else {
      copyToClipboard()
      alert('Content copied to clipboard. You can now paste and share it.')
    }
  }

  function generateNew() {
    topic.value = ''
    context.value = ''
    result.value = ''
    showOutput.value = false
    error.value = ''
    contentType.value = 'paragraph'
    tone.value = 'academic'
    difficulty.value = 'medium'
    wordCount.value = 250
  }

  return {
    // State
    topic,
    context,
    contentType,
    tone,
    difficulty,
    wordCount,
    result,
    loading,
    showOutput,
    error,
    
    // Getters
    wordCountDisplay,
    
    // Actions
    generateContent,
    copyToClipboard,
    downloadTXT,
    downloadPDF,
    shareContent,
    generateNew
  }
})