import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

export const useGeneratorStore = defineStore('generator', () => {
  // State
  const topic = ref('')
  const context = ref('')
  const contentType = ref('paragraph')
  const tone = ref('academic')
  const difficulty = ref('medium')
  const wordCount = ref(250)
  const result = ref('')
  const loading = ref(false)
  const showOutput = ref(false)
  const error = ref('')

  // API URL
  const API_URL = 'https://cactus-pen.onrender.com/api/generate'

  // Getters (computed)
  const wordCountDisplay = computed(() => {
    return result.value ? result.value.trim().split(/\s+/).length : wordCount.value
  })

  // Actions
  const generateContent = async () => {
  error.value = ''
  result.value = ''
  showOutput.value = false
  
  if (!topic.value.trim()) {
    error.value = 'Please enter a topic'
    return
  }

  loading.value = true

  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: { 
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      },
      body: JSON.stringify({
        topic: topic.value,
        context: context.value,
        contentType: contentType.value,
        tone: tone.value,
        difficulty: difficulty.value,
        wordCount: wordCount.value
      })
    })

    // Get the raw response text first
    const responseText = await response.text()
    
    // Try to parse as JSON
    let data
    try {
      data = JSON.parse(responseText)
    } catch (parseError) {
      console.error('Failed to parse JSON:', responseText)
      throw new Error(`Server returned invalid JSON: ${responseText.substring(0, 100)}...`)
    }

    if (!response.ok) {
      throw new Error(data.message || data.error || `HTTP error ${response.status}`)
    }

    if (data.success) {
      result.value = data.result
      showOutput.value = true
    } else {
      error.value = data.message || 'Failed to generate content'
    }

  } catch (err) {
    console.error('Error:', err)
    error.value = `Error: ${err.message}. Please check the backend server.`
  } finally {
    loading.value = false
  }
}

  async function copyToClipboard() {
    try {
      await navigator.clipboard.writeText(result.value)
      return true
    } catch (err) {
      error.value = 'Failed to copy to clipboard'
      return false
    }
  }

  function downloadTXT() {
    const content = `
CACTUS-PEN AI GENERATED CONTENT
================================
Topic: ${topic.value}
Context: ${context.value || 'None'}
Type: ${contentType.value}
Tone: ${tone.value}
Difficulty: ${difficulty.value}
Target Word Count: ${wordCount.value}
Generated: ${new Date().toLocaleString()}

${result.value}
================================
Generated by CactusPen AI - Free AI writing assistant
    `
    
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `cactuspen-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  function downloadPDF() {
    try {
      const pdfContent = `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Cactus-Pen Document</title>
        <style>
          body {
            margin: 1rem;
            padding: 20px;
            background-color: #f0f0f0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            font-family: Arial, sans-serif;
            overflow-x: hidden;
          }
          #canvasContainer {
            max-width: 100%;
            overflow-x: auto;
          }
          canvas {
            background-color: white;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            max-width: 100%;
            height: auto;
            display: block;
          }
          .download-btn {
            position: fixed;
            top: 20px;
            right: 20px;
            padding: 12px 24px;
            background-color: #0aecd0;
            color: #1a2a24;
            border: none;
            border-radius: 6px;
            font-size: 16px;
            font-weight: bold;
            cursor: pointer;
            box-shadow: 0 2px 8px rgba(0,0,0,0.2);
            z-index: 1000;
          }
          .download-btn:hover {
            background-color: #08d4b8;
          }
          @media print {
            body {
              background-color: white;
            }
            .download-btn {
              display: none;
            }
          }
        </style>
      </head>
      <body>
        <button class="download-btn" onclick="downloadCanvas()">Download PDF</button>
        <div id="canvasContainer">
          <canvas id="documentCanvas"></canvas>
        </div>
        
        <script>
          const canvas = document.getElementById('documentCanvas');
          const ctx = canvas.getContext('2d');
          
          canvas.width = 600;
          canvas.height = 800;
          
          // White background
          ctx.fillStyle = 'white';
          ctx.fillRect(0, 0, canvas.width, canvas.height);
          
          // Black border
          ctx.strokeStyle = 'black';
          ctx.lineWidth = 3;
          ctx.strokeRect(10, 10, canvas.width - 20, canvas.height - 20);
          
          // Header - Cactus icon and text
          ctx.fillStyle = '#1a2a24';
          ctx.font = '14px Arial, sans-serif';
          ctx.textAlign = 'center';
          ctx.fillText('🌵 Cactus-pen AI', canvas.width / 2, 50);
          
          // Title - with wrapping for long titles
          ctx.fillStyle = '#1a2a24';
          ctx.font = 'bold 32px Arial, sans-serif';
          const title = '{ ${topic.value} }';
          const titleMaxWidth = 540;
          const titleLines = [];
          const titleWords = title.split(' ');
          let titleLine = '';
          
          for (let i = 0; i < titleWords.length; i++) {
            const testLine = titleLine + titleWords[i] + ' ';
            const metrics = ctx.measureText(testLine);
            if (metrics.width > titleMaxWidth && i > 0) {
              titleLines.push(titleLine.trim());
              titleLine = titleWords[i] + ' ';
            } else {
              titleLine = testLine;
            }
          }
          titleLines.push(titleLine.trim());
          
          let titleY = 95;
          titleLines.forEach((line, index) => {
            ctx.fillText(line, canvas.width / 2, titleY + (index * 40));
          });
          
          const metadataY = 95 + (titleLines.length - 1) * 40 + 30;
          
          // Metadata line
          ctx.font = '12px Arial, sans-serif';
          ctx.fillStyle = '#333';
          ctx.textAlign = 'left';
          ctx.fillText('word count: ${wordCountDisplay.value}', 180, metadataY);
          ctx.fillText('difficulty: ${difficulty.value}', 380, metadataY);
          
          // Content text
          ctx.font = '14px Arial, sans-serif';
          ctx.fillStyle = '#333';
          const text = ${JSON.stringify(result.value)};
          
          const maxWidth = 540;
          const lineHeight = 25;
          let y = metadataY + 40;
          
          const words = text.split(' ');
          let line = '';
          
          for (let n = 0; n < words.length; n++) {
            const testLine = line + words[n] + ' ';
            const metrics = ctx.measureText(testLine);
            
            if (metrics.width > maxWidth && n > 0) {
              ctx.fillText(line, 30, y);
              line = words[n] + ' ';
              y += lineHeight;
              
              // Stop if we reach near the bottom
              if (y > canvas.height - 80) break;
            } else {
              line = testLine;
            }
          }
          ctx.fillText(line, 30, y);
          
          // Footer
          ctx.font = '12px Arial, sans-serif';
          ctx.fillStyle = '#666';
          ctx.textAlign = 'center';
          ctx.fillText('created with: Cactus-AI', canvas.width / 2, canvas.height - 30);
          
          // Download function
          function downloadCanvas() {
            canvas.toBlob(function(blob) {
              const url = URL.createObjectURL(blob);
              const a = document.createElement('a');
              a.href = url;
              a.download = 'cactuspen-${Date.now()}.png';
              document.body.appendChild(a);
              a.click();
              document.body.removeChild(a);
              URL.revokeObjectURL(url);
            });
          }
        <\/script>
      </body>
      </html>
      `
      
      const printWindow = window.open('', '_blank')
      printWindow.document.write(pdfContent)
      printWindow.document.close()
      
    } catch (err) {
      console.error('PDF generation error:', err)
      error.value = 'Failed to generate PDF. Please try again.'
    }
  }

  function shareContent() {
    if (navigator.share) {
      navigator.share({
        title: `CactusPen AI: ${topic.value}`,
        text: result.value.substring(0, 100) + '...',
        url: window.location.href,
      })
      .catch(console.error)
    } else {
      copyToClipboard()
      alert('Content copied to clipboard. You can now paste and share it.')
    }
  }

  function generateNew() {
    topic.value = ''
    context.value = ''
    result.value = ''
    showOutput.value = false
    error.value = ''
    contentType.value = 'paragraph'
    tone.value = 'academic'
    difficulty.value = 'medium'
    wordCount.value = 250
  }

  return {
    // State
    topic,
    context,
    contentType,
    tone,
    difficulty,
    wordCount,
    result,
    loading,
    showOutput,
    error,
    
    // Getters
    wordCountDisplay,
    
    // Actions
    generateContent,
    copyToClipboard,
    downloadTXT,
    downloadPDF,
    shareContent,
    generateNew
  }
})