import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

export const useGeneratorStore = defineStore('generator', () => {
  // State
  const topic = ref('')
  const contentType = ref('paragraph')
  const tone = ref('academic')
  const length = ref('medium')
  const result = ref('')
  const loading = ref(false)
  const showOutput = ref(false)
  const error = ref('')

  // Constants
  const API_URL = 'http://localhost:3000/api/generate'
  
  const lengthMap = {
    short: 100,
    medium: 250,
    long: 500
  }

  // Getters
  const wordCount = computed(() => {
    return result.value ? result.value.trim().split(/\s+/).length : 0
  })

  // Actions
  const generateContent = async () => {
    error.value = ''
    result.value = ''
    showOutput.value = false
    
    if (!topic.value.trim()) {
      error.value = 'Please enter a topic'
      return
    }

    loading.value = true

    try {
      const wordCount = lengthMap[length.value] || 250
      
      const response = await fetch(API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topic: topic.value,
          contentType: contentType.value,
          tone: tone.value,
          wordCount: wordCount
        })
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.message || `HTTP error ${response.status}`)
      }

      if (data.success) {
        result.value = data.result
        showOutput.value = true
      } else {
        error.value = data.message || 'Failed to generate content'
      }

    } catch (err) {
      console.error('Error:', err)
      error.value = `Error: ${err.message}`
    } finally {
      loading.value = false
    }
  }

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(result.value)
      return { success: true, message: '✅ Copied to clipboard!' }
    } catch (err) {
      error.value = 'Failed to copy to clipboard'
      return { success: false, message: 'Failed to copy to clipboard' }
    }
  }

  const downloadTXT = () => {
    const content = `
CACTUS-PEN AI GENERATED CONTENT
================================
Topic: ${topic.value}
Type: ${contentType.value}
Tone: ${tone.value}
Length: ${length.value}
Word Count: ${wordCount.value}
Generated: ${new Date().toLocaleString()}

${result.value}
================================
Generated by CactusPen AI - Free AI writing assistant
    `
    
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `cactuspen-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const downloadPDF = () => {
    try {
      const pdfContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>CactusPen AI - Generated Content</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
          }
          .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 3px solid #2ecc71;
          }
          .metadata {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 30px;
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 10px;
          }
          .content {
            font-size: 14px;
            line-height: 1.8;
            text-align: justify;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1> ${contentType.value} ${topic.value}</h1>
          <p>AI-Powered Writing Assistant</p>
        </div>
        
        <div class="metadata">
          <div class="metadata-item">
            <span class="metadata-label">Topic:</span>
            <span class="metadata-value">${topic.value}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Content Type:</span>
            <span class="metadata-value">${contentType.value}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Tone:</span>
            <span class="metadata-value">${tone.value}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Word Count:</span>
            <span class="metadata-value">${wordCount.value}</span>
          </div>
          <div class="metadata-item">
            <span class="metadata-label">Generated:</span>
            <span class="metadata-value">${new Date().toLocaleString()}</span>
          </div>
        </div>
        
        <div class="content">
          ${result.value.replace(/\n/g, '<br>')}
        </div>
      </body>
      </html>
      `
      
      const printWindow = window.open('', '_blank')
      printWindow.document.write(pdfContent)
      printWindow.document.close()
      
      printWindow.onload = function() {
        printWindow.print()
        printWindow.onafterprint = function() {
          printWindow.close()
        }
      }
      
    } catch (err) {
      console.error('PDF generation error:', err)
      error.value = 'Failed to generate PDF. Please try again.'
    }
  }

  const generateNew = () => {
    topic.value = ''
    result.value = ''
    showOutput.value = false
    error.value = ''
    contentType.value = 'paragraph'
    tone.value = 'academic'
    length.value = 'medium'
  }

  return {
    // State
    topic,
    contentType,
    tone,
    length,
    result,
    loading,
    showOutput,
    error,
    
    // Getters
    wordCount,
    
    // Actions
    generateContent,
    copyToClipboard,
    downloadTXT,
    downloadPDF,
    generateNew
  }
})