// Optional: More advanced PDF export
import { jsPDF } from 'jspdf'

export function generatePDF(content, metadata) {
  const doc = new jsPDF()
  
  // Add header with cactus logo
  doc.setFillColor(46, 204, 113)
  doc.rect(0, 0, 210, 30, 'F')
  
  doc.setFontSize(24)
  doc.setTextColor(255, 255, 255)
  doc.text('🌵 Cactus-pen AI', 20, 20)
  
  // Add metadata
  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text(`Generated: ${new Date(metadata.timestamp || Date.now()).toLocaleString()}`, 20, 40)
  doc.text(`Mode: ${metadata.mode || 'paragraph'} • Tone: ${metadata.tone || 'academic'}`, 20, 45)
  doc.text(`Difficulty: ${metadata.difficulty || 'easy'} • Word Count: ${metadata.wordCount || 200}`, 20, 50)
  
  // Add content
  doc.setFontSize(12)
  doc.setTextColor(0, 0, 0)
  
  const lines = doc.splitTextToSize(content, 170)
  doc.text(lines, 20, 60)
  
  // Add footer
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text('Generated by Cactus-pen AI - Free AI writing assistant for students', 20, 280)
  doc.text('No login required • Privacy first • PDF export • cactuspen.example.com', 20, 285)
  
  return doc
}

export function downloadPDF(content, metadata, filename = 'cactus-pen-output') {
  const doc = generatePDF(content, metadata)
  doc.save(`${filename}-${Date.now()}.pdf`)
}